### PR TITLE
Fix flex2.6.0

### PR DESCRIPTION
**Pull request by rafamanzo**
The macros did not handle the case of flex 2.6.0.

### CODE REVIEW

**Comment by joenio** [comment]
Seems that it already fixed in doxygen repository doxygen/doxygen@cf936efb8ae99dd297b6afb9c6a06beb81f5b0fb
doxygen/doxygen@8c51120ad55b440b738ef0b96f8169d84a7ae88a

I think we can rebase our master branch with these updates, I've updated our doxyparse/upstream against the doxygen/master. What do you think?

ps.: I'm trying to add the doxyparse in the doxygen oficial repository as you can see in doxygen/doxygen#425, I hope the guys there accept our contributions.

**Comment by rafamanzo** [comment]
Sure :)

The rebase is the best option. I've not realised that following doxygen's mainstream have become real, that's awesome news!

**Comment by terceiro** [comment]
the last time I tried rebasing doxyparse on top of a newer doxygen several analizo tests started to fail and I gave up. You will need to look carefully at that.

**Comment by joenio** [comment]
Yes, i know, for now I have only these tests failing analizo/analizo#76 analizo/analizo#77

And, i suppose, the newer doxyparse version fixes the bug analizo/analizo#6

**Comment by joenio** [comment]
While doxygen upstream don't accept the doxyparse I did a new release rebased with the last doxygen stable version. Then I suppose it is solved.

You can find doxyparse's binaries for download here:
- https://github.com/analizo/analizo/wiki/Doxyparse

**Pull request closed without merging**
